apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- if .Values.ccm.failover -}}
  failover: "{{ .Values.ccm.failover }}"
  {{- end }}
  ccm.yaml: |
    config: {{ .Values.config.name | default (include "chart.fullname" .) }}@{{ .Values.config.namespace | default .Release.Namespace }}
    secret: {{ .Values.secret.name | default (include "chart.fullname" .) }}@{{ .Values.secret.namespace | default .Release.Namespace }}
