{{- if not .Values.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data: {}
{{- end }}
