name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@master

      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot

      - uses: actions/upload-artifact@v4
        with:
          path: dist
